data:
    data_dir: "../../data/Algonauts23_shared_Net2Brain/scenes"
    stimuli_path: "../../data/Algonauts23_shared_Net2Brain/scenes/images/"
    brain_rdms: "../../data/Algonauts23_shared_Net2Brain/scenes/brain_data/"
    results_dir: "results/scenes/"
    category: "scenes"

model:
    directory: "../../data/central_vision_ssl"
    name: "resnet50"
    time_window: 0
    crop_size: 540
    center_crop: False

feature_extraction:
    layers:
        - "backbone.layer1"
        - "backbone.layer2"
        - "backbone.layer3"
        - "backbone.layer4"

analysis:
    rsa:
        execute: True
        distance_metric: "spearman"
    reg: 
        execute: True
        n_folds: 3 # stick to net2brain defaults for now
        n_components: 90
        trn_tst_split: 0.9
        batch_size: 100


