data:
    data_dir: "../../data/BOLDmoments/fmri"
    stimuli_path: "../../data/BOLDmoments/stimuli_combined"
    brain_rdms: "../../data/BOLDmoments/rdms"
    results_dir: "results/BOLDmoments/Regression/"
    category: None
model:
    directory: "../../data/central_vision_ssl"
    netset: cv_ssl
    name: "resnet50"
    time_window: 15
    crop_size: 540
    center_crop: False

feature_extraction:
    layers:
        - "backbone.layer4"
    extraction_kwargs: {"pick_frames": 5, "agg_frames": null}
analysis:
    rsa:
        execute: False
        distance_metric: "spearman"
        kwargs: {}
    reg: 
        execute: True
        n_folds: 1
        n_components: 100
        trn_tst_split: custom
        custom_trn_tst: 1000
        batch_size: 100


